//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mostrar.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfActor", Namespace="http://fanta.cl/", ItemName="actor")]
    [System.SerializableAttribute()]
    public class ArrayOfActor : System.Collections.Generic.List<Mostrar.ServiceReference1.actor> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="actor", Namespace="http://fanta.cl/")]
    [System.SerializableAttribute()]
    public partial class actor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int actor_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        private System.Nullable<System.DateTime> last_updateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int actor_id {
            get {
                return this.actor_idField;
            }
            set {
                if ((this.actor_idField.Equals(value) != true)) {
                    this.actor_idField = value;
                    this.RaisePropertyChanged("actor_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> last_update {
            get {
                return this.last_updateField;
            }
            set {
                if ((this.last_updateField.Equals(value) != true)) {
                    this.last_updateField = value;
                    this.RaisePropertyChanged("last_update");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fanta.cl/", ConfigurationName="ServiceReference1.WebServiceActorSoap")]
    public interface WebServiceActorSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://fanta.cl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fanta.cl/HelloWorld", ReplyAction="*")]
        Mostrar.ServiceReference1.HelloWorldResponse HelloWorld(Mostrar.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanta.cl/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Mostrar.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Mostrar.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ListarResult from namespace http://fanta.cl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://fanta.cl/Listar", ReplyAction="*")]
        Mostrar.ServiceReference1.ListarResponse Listar(Mostrar.ServiceReference1.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fanta.cl/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<Mostrar.ServiceReference1.ListarResponse> ListarAsync(Mostrar.ServiceReference1.ListarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://fanta.cl/", Order=0)]
        public Mostrar.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Mostrar.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://fanta.cl/", Order=0)]
        public Mostrar.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Mostrar.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fanta.cl/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar", Namespace="http://fanta.cl/", Order=0)]
        public Mostrar.ServiceReference1.ListarRequestBody Body;
        
        public ListarRequest() {
        }
        
        public ListarRequest(Mostrar.ServiceReference1.ListarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarRequestBody {
        
        public ListarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarResponse", Namespace="http://fanta.cl/", Order=0)]
        public Mostrar.ServiceReference1.ListarResponseBody Body;
        
        public ListarResponse() {
        }
        
        public ListarResponse(Mostrar.ServiceReference1.ListarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://fanta.cl/")]
    public partial class ListarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mostrar.ServiceReference1.ArrayOfActor ListarResult;
        
        public ListarResponseBody() {
        }
        
        public ListarResponseBody(Mostrar.ServiceReference1.ArrayOfActor ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceActorSoapChannel : Mostrar.ServiceReference1.WebServiceActorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceActorSoapClient : System.ServiceModel.ClientBase<Mostrar.ServiceReference1.WebServiceActorSoap>, Mostrar.ServiceReference1.WebServiceActorSoap {
        
        public WebServiceActorSoapClient() {
        }
        
        public WebServiceActorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceActorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceActorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceActorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mostrar.ServiceReference1.HelloWorldResponse Mostrar.ServiceReference1.WebServiceActorSoap.HelloWorld(Mostrar.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Mostrar.ServiceReference1.HelloWorldRequest inValue = new Mostrar.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Mostrar.ServiceReference1.HelloWorldRequestBody();
            Mostrar.ServiceReference1.HelloWorldResponse retVal = ((Mostrar.ServiceReference1.WebServiceActorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mostrar.ServiceReference1.HelloWorldResponse> Mostrar.ServiceReference1.WebServiceActorSoap.HelloWorldAsync(Mostrar.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mostrar.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Mostrar.ServiceReference1.HelloWorldRequest inValue = new Mostrar.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Mostrar.ServiceReference1.HelloWorldRequestBody();
            return ((Mostrar.ServiceReference1.WebServiceActorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mostrar.ServiceReference1.ListarResponse Mostrar.ServiceReference1.WebServiceActorSoap.Listar(Mostrar.ServiceReference1.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public Mostrar.ServiceReference1.ArrayOfActor Listar() {
            Mostrar.ServiceReference1.ListarRequest inValue = new Mostrar.ServiceReference1.ListarRequest();
            inValue.Body = new Mostrar.ServiceReference1.ListarRequestBody();
            Mostrar.ServiceReference1.ListarResponse retVal = ((Mostrar.ServiceReference1.WebServiceActorSoap)(this)).Listar(inValue);
            return retVal.Body.ListarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mostrar.ServiceReference1.ListarResponse> Mostrar.ServiceReference1.WebServiceActorSoap.ListarAsync(Mostrar.ServiceReference1.ListarRequest request) {
            return base.Channel.ListarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mostrar.ServiceReference1.ListarResponse> ListarAsync() {
            Mostrar.ServiceReference1.ListarRequest inValue = new Mostrar.ServiceReference1.ListarRequest();
            inValue.Body = new Mostrar.ServiceReference1.ListarRequestBody();
            return ((Mostrar.ServiceReference1.WebServiceActorSoap)(this)).ListarAsync(inValue);
        }
    }
}
