//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Caja", Namespace="http://cocacola.cl/")]
    [System.SerializableAttribute()]
    public partial class Caja : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AltoField;
        
        private int AnchoField;
        
        private int LargoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Alto {
            get {
                return this.AltoField;
            }
            set {
                if ((this.AltoField.Equals(value) != true)) {
                    this.AltoField = value;
                    this.RaisePropertyChanged("Alto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Ancho {
            get {
                return this.AnchoField;
            }
            set {
                if ((this.AnchoField.Equals(value) != true)) {
                    this.AnchoField = value;
                    this.RaisePropertyChanged("Ancho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Largo {
            get {
                return this.LargoField;
            }
            set {
                if ((this.LargoField.Equals(value) != true)) {
                    this.LargoField = value;
                    this.RaisePropertyChanged("Largo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cocacola.cl/", ConfigurationName="ServiceReference1.CajaWSSOAPSoap")]
    public interface CajaWSSOAPSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://cocacola.cl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/HelloWorld", ReplyAction="*")]
        Proyecto2.ServiceReference1.HelloWorldResponse HelloWorld(Proyecto2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Proyecto2.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name caja from namespace http://cocacola.cl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/Volumen", ReplyAction="*")]
        Proyecto2.ServiceReference1.VolumenResponse Volumen(Proyecto2.ServiceReference1.VolumenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/Volumen", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto2.ServiceReference1.VolumenResponse> VolumenAsync(Proyecto2.ServiceReference1.VolumenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://cocacola.cl/", Order=0)]
        public Proyecto2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Proyecto2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://cocacola.cl/", Order=0)]
        public Proyecto2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Proyecto2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocacola.cl/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VolumenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Volumen", Namespace="http://cocacola.cl/", Order=0)]
        public Proyecto2.ServiceReference1.VolumenRequestBody Body;
        
        public VolumenRequest() {
        }
        
        public VolumenRequest(Proyecto2.ServiceReference1.VolumenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocacola.cl/")]
    public partial class VolumenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Proyecto2.ServiceReference1.Caja caja;
        
        public VolumenRequestBody() {
        }
        
        public VolumenRequestBody(Proyecto2.ServiceReference1.Caja caja) {
            this.caja = caja;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VolumenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VolumenResponse", Namespace="http://cocacola.cl/", Order=0)]
        public Proyecto2.ServiceReference1.VolumenResponseBody Body;
        
        public VolumenResponse() {
        }
        
        public VolumenResponse(Proyecto2.ServiceReference1.VolumenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocacola.cl/")]
    public partial class VolumenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VolumenResult;
        
        public VolumenResponseBody() {
        }
        
        public VolumenResponseBody(int VolumenResult) {
            this.VolumenResult = VolumenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CajaWSSOAPSoapChannel : Proyecto2.ServiceReference1.CajaWSSOAPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CajaWSSOAPSoapClient : System.ServiceModel.ClientBase<Proyecto2.ServiceReference1.CajaWSSOAPSoap>, Proyecto2.ServiceReference1.CajaWSSOAPSoap {
        
        public CajaWSSOAPSoapClient() {
        }
        
        public CajaWSSOAPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CajaWSSOAPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajaWSSOAPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajaWSSOAPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.ServiceReference1.HelloWorldResponse Proyecto2.ServiceReference1.CajaWSSOAPSoap.HelloWorld(Proyecto2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Proyecto2.ServiceReference1.HelloWorldRequest inValue = new Proyecto2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Proyecto2.ServiceReference1.HelloWorldRequestBody();
            Proyecto2.ServiceReference1.HelloWorldResponse retVal = ((Proyecto2.ServiceReference1.CajaWSSOAPSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto2.ServiceReference1.HelloWorldResponse> Proyecto2.ServiceReference1.CajaWSSOAPSoap.HelloWorldAsync(Proyecto2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Proyecto2.ServiceReference1.HelloWorldRequest inValue = new Proyecto2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Proyecto2.ServiceReference1.HelloWorldRequestBody();
            return ((Proyecto2.ServiceReference1.CajaWSSOAPSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.ServiceReference1.VolumenResponse Proyecto2.ServiceReference1.CajaWSSOAPSoap.Volumen(Proyecto2.ServiceReference1.VolumenRequest request) {
            return base.Channel.Volumen(request);
        }
        
        public int Volumen(Proyecto2.ServiceReference1.Caja caja) {
            Proyecto2.ServiceReference1.VolumenRequest inValue = new Proyecto2.ServiceReference1.VolumenRequest();
            inValue.Body = new Proyecto2.ServiceReference1.VolumenRequestBody();
            inValue.Body.caja = caja;
            Proyecto2.ServiceReference1.VolumenResponse retVal = ((Proyecto2.ServiceReference1.CajaWSSOAPSoap)(this)).Volumen(inValue);
            return retVal.Body.VolumenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto2.ServiceReference1.VolumenResponse> Proyecto2.ServiceReference1.CajaWSSOAPSoap.VolumenAsync(Proyecto2.ServiceReference1.VolumenRequest request) {
            return base.Channel.VolumenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto2.ServiceReference1.VolumenResponse> VolumenAsync(Proyecto2.ServiceReference1.Caja caja) {
            Proyecto2.ServiceReference1.VolumenRequest inValue = new Proyecto2.ServiceReference1.VolumenRequest();
            inValue.Body = new Proyecto2.ServiceReference1.VolumenRequestBody();
            inValue.Body.caja = caja;
            return ((Proyecto2.ServiceReference1.CajaWSSOAPSoap)(this)).VolumenAsync(inValue);
        }
    }
}
